site_name: jsPsych Hackathons
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'green'
    accent: 'orange'
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/jspsych'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/joshdeleeuw'
  version:
    provider: mike
  analytics:
    provider: google
    property: 'UA-HACKATHON-ID'

copyright: 'Copyright &copy; 2025 jsPsych Community'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: 'https://github.com/jspsych/hackathon'
repo_name: 'jspsych/hackathons'
edit_uri: edit/main/docs
site_url: 'https://www.hackathon.jspsych.org/'
docs_dir: docs

nav:
- Home: 'index.md'
